#include "adapters/cli/cli_adapter.h"

#include <exception>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include <string_view>

#include "adapters/cli/console_diagnostics_reporter.h"
#include "adapters/filesystem/filesystem_output_writer.h"
#include "adapters/filesystem/filesystem_source_lister.h"
#include "adapters/filesystem/filesystem_source_reader.h"
#include "application/codegen_mode.h"
#include "application/compile_pipeline.h"
#include "domain/ast/ast_printer.h"
#include "domain/ast/module.h"
#include "domain/lexer/token_type_name.h"
#include "domain/semantic/typed_printer.h"

namespace cythonpp::adapters::cli {

namespace {

// Which of the three mutually-exclusive dumps the CLI should print. A third
// bool alongside dump_tokens would admit a meaningless fourth (tokens AND
// types) state, so this is an enum instead.
enum class OutputMode { Tokens, Tree, Types };

// Renders control characters visibly so a NEWLINE or TAB token does not
// wreck the column alignment of the dump. Presentation only, which is why it
// lives here rather than in the domain.
std::string escape_lexeme(const std::string& lexeme) {
    std::string escaped;
    escaped.reserve(lexeme.size());
    for (char c : lexeme) {
        switch (c) {
            case '\n': escaped += "\\n"; break;
            case '\t': escaped += "\\t"; break;
            case '\r': escaped += "\\r"; break;
            case '\\': escaped += "\\\\"; break;
            case '"': escaped += "\\\""; break;
            default: escaped += c; break;
        }
    }
    return escaped;
}

void print_module(const std::string& path, const domain::lexer::TokenStream& tokens) {
    std::cout << "=== " << path << " (" << tokens.size() << " tokens) ===" << std::endl;
    for (const domain::lexer::Token& token : tokens) {
        std::cout << std::setw(6) << token.line_number() << ':' << std::left << std::setw(4)
                  << token.column_number() << ' ' << std::setw(24)
                  << domain::lexer::token_type_name(token.type()) << " \""
                  << escape_lexeme(token.lexeme()) << '"' << std::right << std::endl;
    }
}

void print_tree(const std::string& path, const domain::ast::Module& module) {
    std::cout << "=== " << path << " ===" << std::endl;
    std::cout << domain::ast::AstPrinter().print(module) << std::endl;
}

void print_typed_tree(const std::string& path, const domain::ast::Module& module,
                       const domain::semantic::TypeMap& types) {
    std::cout << "=== " << path << " ===" << std::endl;
    std::cout << domain::semantic::TypedPrinter().print(module, types) << std::endl;
}

void print_result(const application::CompileResult& result, OutputMode mode) {
    std::size_t total = 0;
    for (const auto& module : result.modules) {
        switch (mode) {
            case OutputMode::Tokens:
                print_module(module.first, module.second.tokens);
                total += module.second.tokens.size();
                break;
            case OutputMode::Tree:
                print_tree(module.first, *module.second.ast);
                break;
            case OutputMode::Types:
                print_typed_tree(module.first, *module.second.ast, module.second.types);
                break;
        }
    }
    if (mode == OutputMode::Tokens) {
        std::cout << result.modules.size() << " files, " << total << " tokens" << std::endl;
    } else {
        std::cout << result.modules.size() << " files" << std::endl;
    }
}

// Written as the first line of every .cpp this compiler emits, so a LATER
// run can tell "this file is stale output from an earlier --emit-cpp run"
// apart from "this happens to be some other file that landed at the same
// path" -- a real distinction, since silently deleting a file this compiler
// never wrote because the user's program failed to compile would be a worse
// defect than the stale-output problem the marker exists to fix.
constexpr std::string_view kGeneratedMarker =
    "// Generated by cythonpp -- do not edit by hand; regenerate with --emit-cpp.";

// True only when `path` exists and its first line is exactly the marker
// above, i.e. cythonpp itself wrote it on some earlier run. False for a
// missing path, an unreadable one, or a file some other tool or the user
// created -- and that "false" answer is what makes removal safe: it is
// never true for a file this compiler did not itself produce, regardless of
// its extension or where it sits.
bool looks_cythonpp_generated(const std::filesystem::path& path) {
    std::ifstream file(path);
    if (!file) {
        return false;
    }
    std::string first_line;
    std::getline(file, first_line);
    return first_line == kGeneratedMarker;
}

// Removes a stale target left by a PREVIOUS successful --emit-cpp run, for a
// module that no longer emits successfully -- so a regression (a program
// that used to compile and now does not) does not leave an old .cpp on disk
// indistinguishable from current output. Guarded by
// looks_cythonpp_generated: a target path that exists but was never written
// by cythonpp (a user's own same-named .cpp, say) is left completely alone,
// on the reasoning above -- deleting a file we did not create because we
// could not compile something would be strictly worse than leaving a stale
// one in place.
void remove_stale_target_if_ours(const std::filesystem::path& path) {
    if (looks_cythonpp_generated(path)) {
        std::filesystem::remove(path);
    }
}

// Writes every module's emitted source to disk, at its own input path with
// the extension replaced by ".cpp", and reconciles a stale target for any
// module that no longer emits. Two independent actions, not one gate:
//
//  - REMOVAL runs per module, unconditionally. A module whose `cpp` is
//    nullopt (it failed somewhere -- parse, type check, or a codegen
//    refusal) has any stale .cpp OF ITS OWN removed, regardless of whether
//    some OTHER module in this same run also failed or succeeded. A
//    regression in file A must not leave file A's stale artifact behind
//    just because file B failed too, and it must not touch file B's
//    artifact either -- each module's staleness is its own concern, not the
//    whole run's.
//
//  - WRITING new content stays gated on the WHOLE run being error-free, and
//    that gate is NOT there to stop an uncompilable .cpp from reaching disk
//    -- compile_one already guarantees that by leaving `cpp` nullopt for
//    any module that failed, so there is no bad content here to accidentally
//    write in the first place. The real reason is consistency: a directory
//    run that updated some .cpp files to reflect the latest source while
//    silently leaving others on a stale prior version is a confusing result
//    to hand back to a caller, so a run is all-or-nothing for NEW content
//    the same way it already is for the exit code. Whether to relax this
//    into partial emission is a separate decision, not made here.
void write_emitted_sources(const application::CompileResult& result) {
    filesystem::FilesystemOutputWriter output_writer;
    for (const auto& module : result.modules) {
        std::filesystem::path output_path(module.first);
        output_path.replace_extension(".cpp");
        if (module.second.cpp.has_value()) {
            if (!result.has_errors) {
                output_writer.write(output_path.string(),
                                     std::string(kGeneratedMarker) + "\n" + *module.second.cpp);
            }
        } else {
            remove_stale_target_if_ours(output_path);
        }
    }
}

} // namespace

int CliAdapter::run(int argc, char** argv) {
    OutputMode mode = OutputMode::Tree;
    bool emit_cpp = false;
    std::string path;
    for (int index = 1; index < argc; ++index) {
        const std::string argument = argv[index];
        if (argument == "--tokens") {
            mode = OutputMode::Tokens;
        } else if (argument == "--types") {
            mode = OutputMode::Types;
        } else if (argument == "--emit-cpp") {
            // A separate flag, not a fourth OutputMode: the three existing
            // modes all print a dump to stdout, while this one writes a
            // file, and it can combine with any of them.
            emit_cpp = true;
        } else if (path.empty()) {
            path = argument;
        } else {
            std::cerr << "unexpected argument: " << argument << std::endl;
            return 1;
        }
    }
    if (path.empty()) {
        std::cerr
            << "usage: cythonpp [--tokens|--types] [--emit-cpp] <path-to-python-file-or-directory>"
            << std::endl;
        return 1;
    }

    filesystem::FilesystemSourceReader source_reader;
    filesystem::FilesystemSourceLister source_lister;
    ConsoleDiagnosticsReporter diagnostics_reporter;
    application::CompilePipeline pipeline(source_reader, source_lister, diagnostics_reporter);

    // CodegenMode has no default (see codegen_mode.h) precisely so this
    // choice cannot be forgotten: Skip for every other invocation, since
    // running the emitter unconditionally would report codegen's own
    // NotImplementedError refusals for a program the user only asked to see
    // tokenized or typed, never to compile.
    const application::CodegenMode codegen =
        emit_cpp ? application::CodegenMode::Emit : application::CodegenMode::Skip;

    try {
        // Interpreting argv is this adapter's job. Asking the OS whether a
        // path is a directory needs <filesystem>, which the application
        // layer must not depend on -- so the choice is made here, at the
        // composition root, and the pipeline just exposes two verbs.
        const application::CompileResult result = std::filesystem::is_directory(path)
                                                      ? pipeline.compile_directory(path, codegen)
                                                      : pipeline.compile_file(path, codegen);
        print_result(result, mode);

        // Called unconditionally (not gated on !result.has_errors here) --
        // write_emitted_sources itself decides, per module, whether to
        // write fresh content or remove a stale target; see its own comment
        // for why those are two separate questions rather than one gate.
        if (emit_cpp) {
            write_emitted_sources(result);
        }

        // The tree is still printed for a file with errors -- seeing the
        // output is exactly what helps when diagnosing one -- but the exit
        // code has to say the compile failed.
        return result.has_errors ? 1 : 0;
    } catch (const std::exception& error) {
        // Wider than runtime_error: <filesystem> throws filesystem_error and
        // TokenStream::at throws out_of_range, both worth reporting rather
        // than terminating on.
        std::cerr << error.what() << std::endl;
        return 1;
    }
}

} // namespace cythonpp::adapters::cli
